replicaCount: 1

image:
  repository: ghcr.io/b-otunga/currency-api
  tag: sha256:53880661bf2b44843f5e40912713956aac421615b5d8c125d83d8310ef217791
  pullPolicy: IfNotPresent

env:
  APP_ENV: dev
  APP_VERSION: "1.0.0"
  USE_LIVE_RATES: "false"
  FORCE_UNHEALTHY: "false"

service:
  port: 8000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
